### ISSUE TITLE
Request - Features

### ISSUE THREAD

**Issue by AndresPataFM** [teroparvinen/foundry-wire#1]
This is an amazing module that Im loving so far but there are 2n main areas of improvement that I would love to see:

1. Hiding information from players as a DM: Is it possible in a future update to hide creature AC from players and options to hide Dice / Modifiers?
2. Modifying rolls after it is done (basically features from Ready Set Roll for 5e): Being able to modify an attack after its is declared if someone forgets advantage/disadvantage and being able to turn damage into critical damage if desired.

This seems to be the best option out there and I will try testing it these weeks, i will post any bug that I find

**Comment by AndresPataFM** [comment]
Here it is from gamemaster point of view
![image](https://user-images.githubusercontent.com/76007985/206254636-e2b7aa8e-bdcf-43de-91f2-34f39bb29f82.png)
Here it is from a player point of view
![image](https://user-images.githubusercontent.com/76007985/206254946-4b30fa7e-a321-4746-90f2-6a547a59f7b5.png)
Adding a PC to the mix (Dungeonmaster side)
![image](https://user-images.githubusercontent.com/76007985/206255900-5cd2fce5-788c-421e-9961-e469057dece7.png)
Player Side
![image](https://user-images.githubusercontent.com/76007985/206256259-0b017a50-b702-42b4-b027-1e048e8b9115.png)

My modules at the time of testing:

```
Active Modules:
----------
Advanced Macros v;
Ammo Tracker v;
Automated Animations v;
Beaver's Crafting System v;
Burger Time v;
Chat Images v;
Combat Utility Belt v;
Compendium Folders v;
Custom CSS v;
DFreds Convenient Effects v;
DFreds Droppables v;
DF Template Enhancements v;
Dice So Nice! v;
DnD5e Drag Ruler Integration v;
Drag Ruler v;
Dynamic Active Effects SRD v;
Dynamic effects using Active Effects v;
Entice with Dice so Nice v;
Foundry VTT Anniversary Dice Set by The Rollsmith v;
FXMaster v;
Hourglass v;
Image Hover v;
Initiative Double Click v;
Item Macro v;
JB2A - Jules and Ben's Animated Assets - Free Content v;
Less Fog v;
lib - Color Settings v;
Library: Active effect manager v;
libWrapper v.0;
Lordu's Custom Dice for Dice So Nice v;
Macro Folders v;
Merchant Sheet NPC v;
Monk's Active Tile Triggers v;
Monk's Enhanced Journal v;
Monk's Little Details v;
Monk's Shops v;
Monk's Sound Enhancements v;
Monk's TokenBar v;
Monk's Wall Enhancement v;
Multilevel Tokens v;
Nice more Dice v;
Perfect Vision v;
PnP - Pointer and Pings! v;
Sequencer v;
Simple Calendar v;
socketlib v;
SoundFx Library v;
Spell Level Buttons for DnD 5e v;
Split Journal v;
Storyteller v;
The Furnace v;
Tidy5e Sheet v;
Tidy UI - Game Settings v;
Times Up v;
Token HUD Wildcard (fix) v;
Token Magic FX v;
Variant Encumbrance+Midi v;
Viejopedia v;
Warp Gate v;
Whistler's Item Rolls Extended v;
Whistler's Item Rolls Extended - SRD Items v;
WikiRole for Dice So Nice v;

Inactive Modules:
----------
Hide GM Rolls v;
Midi QOL v;
Ready Set Roll for D&D5e v;
```

**Comment by cstby** [comment]
I think I understand what's happening. When the roll is initiated by the GM, the creature's AC will be displayed in the card. When the roll is initiated by a player, the AC will be hidden.

If your PCs only attack NPCs and your NPCs only attack PCs, then it shouldn't be a problem.

Here are the situations where this could be a problem:
- The GM controls a (probably friendly) NPC who makes attacks against a creature whose AC should be hidden from the players.
- The GM wants the players' AC to be hidden from other players.

**Comment by AndresPataFM** [comment]
Well that is the current work around, I hope that a beter implementation can be done on a future update down the line.
