### ISSUE TITLE
[Bug] Apply to Self toggles not working

### ISSUE THREAD

**Issue by roguedevjake** [teroparvinen/foundry-wire#10]
**Issue**
In the effect configuration screen setting the following toggles don't work:
- Apply to self when item applies target effects
- Apply to self when item is rolled

It will apply the effect to the target, if there is a roll involved it won't apply the effect until after that roll is made and then reapply it immediately (removing the effect from the target).

Example of a use case scenario, battle master's trip attack, gives a 1d8 to the user's next damage roll and forces the target to make a save against their maneuver DC to avoid being made prone.

**Comment by teroparvinen** [comment]
Those fields are generated by DAE (module) and I didn't write any code to hide them, although maybe I should. It is an example of DAE being somewhat intended to be used with midi-qol. WIRE does not use them.

To make battle master maneuvers, look at smites here: https://github.com/teroparvinen/foundry-wire-examples

Basically, here's how you'd use it (ignore the fact that smite spells as bonus actions need to be activated before attacking, this is how the maneuver would work)

- Make an attack roll
- The DM calls for hit/miss
- If it hit and you decide to use the ability, activate it
- Roll damage and you get the desired results

Here's how it works technically

- There are two effects on the spell/ability
    - One is set to immediate, it is applied to the paladin/battlemaster (despite the attack target being something else because the item has a target of Self). It has a condition to apply delayed effects when a melee weapon attack hits. It also has an effect row that adds the bonus damage (to the paladin/battlemaster).
    - The other is set to delayed and contains the status
- The item macro specifies a custom flow for delayed effects. The important bit is `this.applyTargetFromCondition` which sets the target for subsequent operations (the prone status) to be the target of the attacker.

You should be able to just copy paste the item macro to maneuvers.
