### ISSUE TITLE
Wire + libWrapper incrementing ADD effects

### ISSUE THREAD

**Issue by eliswen** [teroparvinen/foundry-wire#12]
Hey, I made a comment on your reddit thread, and you asked me to make an official bug report. So, here it is.

To reproduce the issue:

-Foundry VTT 10.291
-DnD 5e 2.0.3

1) Disable all modules except WIRE and libWrapper
2) Create an actor and give it hit points
3) Make a Passive Effect on that actor thusly: system.attributes.hp.max ADD 1
4) Create a token for that actor
5) Open its character sheet from the token, close it, and open it again
6) Repeat 5 a few times

You should watch the HP max value increment by 1 every time you open the actor sheet.

I have tested this by enabling and disabling modules in various configurations. If you disable everything except WIRE, it's fine. As soon as you enable libWrapper, the incrementing problem starts. If I enable every module except libWrapper, it stops. If I keep libWrapper and disable Wire, it stops.

I'm sure this is doing other things, but I have no idea why.

**Comment by teroparvinen** [comment]
This one was introduced in the upgrade to version 10. Thanks for the report, will be fixed in the next update.
