### ISSUE TITLE
Item Usage Consumption seems broken?

### ISSUE THREAD

**Issue by GebotheBardbarian** [teroparvinen/foundry-wire#14]
I've used Find the Culprit and pinpointed it to WIRE, not sure which of the latest updates may have changed it, though.

In the example, the Potion of Heroism used is the one from the WIRE SRD compendium.

![image](https://user-images.githubusercontent.com/74924680/209052666-ef5d8999-f11a-4e5c-ab5e-aa5aef377303.png)

With the "Consume Available Usage?" box checked:

![image](https://user-images.githubusercontent.com/74924680/209052718-9cb343e1-9049-4dcb-aba9-f4fbaab9f5f6.png)

I get this error:

![image](https://user-images.githubusercontent.com/74924680/209052863-4cefb086-4ebc-4770-a04f-41c5f4a93cc6.png)

Console log:

![image](https://user-images.githubusercontent.com/74924680/209052990-9ffe810e-e41a-4858-aab8-3d69c22e62f1.png)

If I uncheck the Usage box, all works as expected. The same occurred with a new item I made fresh, as well.

**Comment by teroparvinen** [comment]
Thank you for reporting, basic stuff like this is super valuable. The issue here was that the potion was deleted before its use was completed. It will be resolved in the next update.
