### ISSUE TITLE
Request: Setting to turn off panning to current combatant

### ISSUE THREAD

**Issue by GebotheBardbarian** [teroparvinen/foundry-wire#15]
Would it be possible to implement a client setting to turn off panning to each combatant on their turn? I'm not a fan....

**Comment by teroparvinen** [comment]
Absolutely. For what it's worth, it's just for the GM, but I'll get it into the next version.

**Comment by GebotheBardbarian** [comment]
Amazing! Thank you for such quick responses, too, btw!
