### ISSUE TITLE
[Issue] Variant Prompt

### ISSUE THREAD

**Issue by SosukeAizen** [teroparvinen/foundry-wire#18]
I created an active ability feature on a character, while going through the new options I clicked the + to add a new variant, then unsure of what it was for removed it, however, now whenever the feature is rolled a dialog for the variant comes up even though there aren't any.

![image](https://user-images.githubusercontent.com/15948761/209677836-4ea8e577-89fe-4ccf-b6c1-5580087efdfc.png)

I'm very new to this module so apologies if this is ignorance on my part.

Thank you.

**Comment by teroparvinen** [comment]
I recently fixed this, will be in an upcoming update. Thanks for reporting!
