### ISSUE TITLE
Damage Calc Rolling Pub

### ISSUE THREAD

**Issue by tribbell** [teroparvinen/foundry-wire#22]
The damage calculation is posting publicly, instead of a Private GM Roll, letting players see HP numbers:
![image](https://user-images.githubusercontent.com/121588568/209890167-6c6a9c3d-241a-47ef-9cde-17120d28a960.png)

**Comment by teroparvinen** [comment]
It should reveal damage for characters with a player owner. For me it seems to be working correctly.

If there is a situation where it is showing NPC damage, this would be a bug, but then I need some more detailed replication steps or more information about how you have set up the characters and tokens.

**Comment by YenBenGrey** [comment]
I noticed this yesterday. It was only showing for owned PCs or owned characters. 

It wasn’t showing for NPCs/Monsters when I was signed in as a player.

**Comment by tribbell** [comment]
Ah, understood.
