### ISSUE TITLE
Error: Saving Throws + Effects that add dice to the roll don't work, produce error

### ISSUE THREAD

**Issue by DreamingHero1997** [teroparvinen/foundry-wire#23]
![image](https://user-images.githubusercontent.com/84264700/209966050-c7416d36-e6bd-4bd9-a763-e0f672b966f9.png)
I was testing out the newest update and while testing I tried out bless but it didn't produce any saving throws, instead it gave the error seen above.

**Comment by teroparvinen** [comment]
Yikes. I will put this to the top of the todo list.

**Comment by teroparvinen** [comment]
Thank you for the report. Should now be fixed with the update.
