### ISSUE TITLE
WIRE not rolling attacks or Damage

### ISSUE THREAD

**Issue by ctbritt** [teroparvinen/foundry-wire#25]
Not sure what the issue is. It's just not rolling any attacks or damages. This is the error I'm consistently getting:
![image](https://user-images.githubusercontent.com/4516034/209991019-c7496ef3-83a2-49f3-88d5-074614e2fb59.png)
And these are my active modules: 
```
### Active Modules
Action Pack v10.6 [Bugs URL](https://github.com/teroparvinen/foundry-action-pack/issues)
DFreds Convenient Effects v3.1.0 [Bugs URL](https://github.com/DFreds/dfreds-convenient-effects/issues)
DFreds Effects Panel v2.0.2 [Bugs URL](https://github.com/DFreds/dfreds-effects-panel/issues)
DF Template Enhancements v1.3.0 [Bugs URL](https://github.com/flamewave000/dragonflagon-fvtt/issues)
Dynamic effects using Active Effects v10.0.14 [Bugs URL](https://gitlab.com/tposney/dae/-/issues)
Dynamic Active Effects SRD v6.0.01 [Bugs URL](https://github.com/kandashi/Dynamic-Effects-SRD/issues)
Find the culprit v1.4.6 [Bugs URL](https://github.com/Moerill/fvtt-find-the-culprit/issues)
Item Macro v1.8.0
libWrapper v1.12.11.0 [Bugs URL](https://github.com/ruipin/fvtt-lib-wrapper/issues)
socketlib v1.0.12 [Bugs URL](https://github.com/manuelVo/foundryvtt-socketlib/issues)
Module Management+ v2.1.5 [Bugs URL](https://github.com/mouse0270/module-credits/issues)
Quick Insert - Search Widget v2.8.0 [Bugs URL](https://gitlab.com/fvtt-modules-lab/quick-insert/-/issues)
Sequencer v2.4.2 [Bugs URL](https://github.com/fantasycalendar/FoundryVTT-Sequencer/issues)
Automated Animations v4.1.00
SharedData v1.1
Tidy5e Sheet v0.7.4
Whistler's Item Rolls Extended v0.10.6 [Bugs URL](https://github.com/teroparvinen/foundry-wire/issues)
Whistler's Item Rolls Extended - Example Items v0.10 [Bugs URL](https://github.com/teroparvinen/foundry-wire-examples/issues)
Whistler's Item Rolls Extended - SRD Items v0.10.1 [Bugs URL](https://github.com/teroparvinen/foundry-wire-srd/issues)
```
not sure what happened, as it was working in earlier versions. Could there be a world setting that's borking it?

**Comment by teroparvinen** [comment]
This is something that clearly should not happen, but there is a place in code where another module could mess it up. 

Basically what is happening is something is stripping the chat message being created of all whisper information. That information indicates which players can see a chat card. It is possible in regular Foundry use for this list to be empty (that is what a public message is), but even in that case the list should still be there, despite being empty. Something is now removing the entire list on the code level.

Is there a module that could do something like this that would give you a clue about which modules to disable? I would nevertheless recommend trying to disable modules one at a time and see if that helps.

**Comment by ctbritt** [comment]
Reducing my add-ons to this: 
<img width="671" alt="CleanShot 2022-12-29 at 23 40 39@2x" src="https://user-images.githubusercontent.com/4516034/210035181-983f4945-ee57-4a35-b8fc-0f1f2dc99476.png">

And I'm still getting the same error. It just will not roll attacks or damage. Not sure what to do at this point. There's nothing that seems to be affecting the chat box.

**Comment by ctbritt** [comment]
More on the console error: 
<img width="470" alt="CleanShot 2022-12-29 at 23 41 58@2x" src="https://user-images.githubusercontent.com/4516034/210035247-7521fd72-c5af-4f7a-8f5c-42c715a0588f.png">

**Comment by teroparvinen** [comment]
A bit more detective work, and I've managed to replicate this with some weird trickery.

In the console (at the bottom there's an empty line for input), could you run this command: `game.settings.get("core", "rollMode")`? If you get something like `null`, this is almost certainly the problem.

To fix it, select something from the roll mode dropdown above the chat box, but please run the command before touching the dropdown so we get confirmation about the source of the problem :)

**Comment by ctbritt** [comment]
Ok. not sure what happened, but I woke up this morning. Reactivated the WIRE modules and they work. I didn't have to do anything. So that's very weird.
