### ISSUE TITLE
Effects not expiring

### ISSUE THREAD

**Issue by DreamingHero1997** [teroparvinen/foundry-wire#26]
Like recommended in the changelog I have removed times up, however now effects will not expire upon their duration reaching 0, they stay active on the sheet but their duration is just set to none.

**Comment by teroparvinen** [comment]
Can you list some specifics, like is the duration in seconds or rounds and was the effect cast while a combat was running?

**Comment by DreamingHero1997** [comment]
I figured it out, I was testing on a gridless map and it seems that for some reason it wasn't ending effects with time passing and some other conditions on that map, seemingly no issues with the same effects on a gridded map.
From previous use cases I already figured out gridless maps don't work nice with the module but I wasn't aware I was doing my testing on one of those maps when I had this issue.
