### ISSUE TITLE
Allow Wounded condition to be applied as an overlay

### ISSUE THREAD

**Issue by jstapels** [teroparvinen/foundry-wire#27]
Simple request to add a configuration option so that when a creature is Wounded and the option to apply that condition is enabled, that the condition can will be applied as an "overlay". This is already supported in the API, so the change is essentially something like...

`wrappers.js:138`
```javascript
            if (needsWounded != hasWounded) { await ceApi.toggleEffect("Wounded", { overlay: overlayConfigured, uuids: [actor.uuid] }); }
```

I can make a pull request which this change as well if that's easier for you.

**Comment by teroparvinen** [comment]
Don't need a PR, I will just put this on the todo list.

Do you use the Damaged condition? Do you think it should share the same flag with wounded, i.e. if Damaged is in use, it would also be applied as an overlay?

**Comment by jstapels** [comment]
Good question which I don't have a good answer for. We don't currently use Damaged but I'm considering trying it out. I would say it's probably better to let it share the same flag to keep the options simpler, although everyone has their own personal preference 😄 .

**Comment by teroparvinen** [comment]
Yeah I'm going to go with that for now.

**Comment by YenBenGrey** [comment]
I know this is complete but just out of interest, what does an overlay look like compared to an icon on the token? I use damaged and would want damaged to be consistent with wounded just to add my two pence worth.

**Comment by jstapels** [comment]
Below is standard on the left, overlay on the right.

<img width="310" alt="StandardVsOverlay" src="https://user-images.githubusercontent.com/113529/210270603-06f9b1f6-ab7b-4d4d-804e-64fc2b168e27.png">

**Comment by YenBenGrey** [comment]
Ah right thank you. Overlay for me.
