### ISSUE TITLE
Item doesn't work with variant setup

### ISSUE THREAD

**Issue by DreamingHero1997** [teroparvinen/foundry-wire#28]
![image](https://user-images.githubusercontent.com/84264700/210765367-9d888e6f-65fc-488c-83de-9599c87a21dd.png)
I get this error when rolling damage for a modified spell I made, I tested it in an environment where only WIRE and its supported/beneficiary modules are present.
I've also attached the spell in question, I have no idea why it's messing up.
[fvtt-Item-life-transference.zip](https://github.com/teroparvinen/foundry-wire/files/10351550/fvtt-Item-life-transference.zip)

**Comment by teroparvinen** [comment]
I managed to get this error when I deleted the effect applied in the "resolving" phase while the spell resolution was still going on. I will see if I can fix this, but I should not be very disruptive, i.e. if the spell is functioning properly, this should not happen.

**Comment by teroparvinen** [comment]
To clarify, with this option selected:
![image](https://user-images.githubusercontent.com/1235386/210776411-12fa922c-cdb8-43a1-915d-2aaa2234e522.png)

**Comment by DreamingHero1997** [comment]
It seems the latest update has indeed fixed the issues with the item, so I'm closing this ^^
