### ISSUE TITLE
Issue: Concentration DC resets to 10 when rolling saving throw.

### ISSUE THREAD

**Issue by DreamingHero1997** [teroparvinen/foundry-wire#34]
![image](https://user-images.githubusercontent.com/84264700/212059130-f15311a8-de10-4838-9139-458b9ab287f5.png)
![image](https://user-images.githubusercontent.com/84264700/212059375-0beb0059-9c6f-43ff-b179-e466f74126d3.png)

As the images show, the concentration seems to reset when the saving throw is rolled, 
Console shows no indication as to why this happens.

**Comment by YenBenGrey** [comment]
Just tested and can confirm this is happening for me too. I’ve just tested too that the DC was 12 and the actor rolled a 10 and it saved and the card reverted to 10.
