### ISSUE TITLE
[Issue] Wire is blocking the function to create new actors

### ISSUE THREAD

**Issue by Schnix1328** [teroparvinen/foundry-wire#37]
Hi,
I tried to create new actors and I get always an error message. Please check the attached file.
After deactivating Wire I can create actors again.

<img width="800" alt="Screenshot 2023-01-18 193941" src="https://user-images.githubusercontent.com/11362203/213266636-c5f2c368-f0f4-44b2-ab8c-3fe7a75d9991.png">

**Comment by teroparvinen** [comment]
WIRE doesn't use the `hasOwnProperty` displayed in the error message. There is probably more in the error console. Can you add any information there to this issue as well?

**Comment by Schnix1328** [comment]
Can you pleaswe tell me where I can find the error logs?

**Comment by teroparvinen** [comment]
This is probably related to #35, and is caused by another module. You can probably get around this by updating the other module in the near future.
