### ISSUE TITLE
avoid green/red font color when the dice roll isn't nat 20/1

### ISSUE THREAD

**Issue by cstby** [teroparvinen/foundry-wire#4]
Currently, WIRE uses green and red colored font to indicate whether a saving throw is a success or failure respectively. Foundry itself already uses this styling to indicate a natural 20 or natural 1. Using the same styling in multiple places to mean different things may confuse some users.

I'd suggest changing the saving throw success/failure styling to the same checkmark and "X" styling used for hit/miss on attack rolls. This would be more internally consistent within WIRE.  It would also avoid overloading the meaning the styling.

Below is the result of a successful save.
![image](https://user-images.githubusercontent.com/45189177/206091824-6e0eaaa7-1dca-4d8e-81cd-920843bbbf2f.png)

Below is a successful attack roll.
![image](https://user-images.githubusercontent.com/45189177/206091878-aaeacf42-8fbc-490e-b3bc-caf463abacd2.png)

Below is a successful attack roll that's a critical hit.
![image](https://user-images.githubusercontent.com/45189177/206092024-a17c18e9-c55b-4d40-91e9-cf7c82b82ae0.png)

**Comment by teroparvinen** [comment]
I think green being success and red being failure is quite a strong convention I'm not willing to give up right now. 

I agree having something other than "success" for a crit might be desirable, but I'm a bit hesitant to go against the convention here.

Green is used for hp and red for damage on the damage card as well, and I think having some color always helps digest information at a glance. Here it'll just have to do to link it to context.
