### ISSUE TITLE
[Bug] Dexterity Tiebreaker is added as text to the roll result instead of addition

### ISSUE THREAD

**Issue by FurtherV** [teroparvinen/foundry-wire#43]
When WIRE is installed and the "Dexterity Tiebreaker" option is enabled the tiebreaker value is concatenated to the roll result, probably because of javascript shenanigans.

For example, take a normal initiative roll of a creature with DEX 20, it would look like this: `1d20 + 5 + 0.2` but with WIRE its actually `1d20 + 5 + "" + 0.2`, so random quotations appear in the roll formula.

Take following image as an example where the upper message is without WIRE while the bottom message is with WIRE.
![image](https://user-images.githubusercontent.com/18612183/218847259-52ba4180-c098-4bee-938d-4b80d4d86e94.png)

**Comment by FurtherV** [comment]
It seems that, in the following function, you turn an empty string into an quoted string. Not sure why but if you'd remove that it would fix it.

```
function formatReplacementResult(value) {
    if (Array.isArray(value)) {
        return value.length ? value.map(v => formatReplacementResult(v)).join() : "undefined";
    } else {
        const str = String(value).trim();
        const isQuotable = str.match(/^[a-z][\w\s\.-]*$/i) || str === "";
        return isQuotable ? `"${str}"` : str;
    }
}
```

**Comment by teroparvinen** [comment]
I think this has been fixed at the source, i.e. the system
