### ISSUE TITLE
Error occurs when casting Concentration spell using WIRE + DFred's Convenient Effects

### ISSUE THREAD

**Issue by lambc42** [teroparvinen/foundry-wire#47]
I'm considering moving away from Midi-QoL to WIRE, so I set up a new world and enabled WIRE and all of the modules recommended in the WIRE wiki. 

The issue I'm running into is that whenever I cast a Concentration spell, I get the error:

A technical error has occurred. Please check the console error log and notify the GM. 

In the console I get the following:

A technical error occurred. Please check the console error log and notify the GM. [foundry.js:59187:78](http://myfoundryserver:30000/scripts/foundry.js)
    fetch http://myfoundryserver:30000/scripts/foundry.js:59187
    notify http://myfoundryserver:30000/scripts/foundry.js:59114
    error http://myfoundryserver:30000/scripts/foundry.js:59150
    handleError http://myfoundryserver:30000/modules/wire/module/utils.js:481
    _activate http://myfoundryserver:30000/modules/wire/module/activation.js:359
A technical error occurred. Please check the console error log and notify the GM. TypeError: uuid is undefined
    _parseUuid http://myfoundryserver:30000/scripts/foundry.js:4176
    fromUuidSync http://myfoundryserver:30000/scripts/foundry.js:4140
    getActorByUuid http://myfoundryserver:30000/modules/dfreds-convenient-effects/scripts/foundry-helpers.js:43
    hasEffectApplied http://myfoundryserver:30000/modules/dfreds-convenient-effects/scripts/effects/effect-handler.js:47
    hasEffectApplied http://myfoundryserver:30000/modules/dfreds-convenient-effects/scripts/effect-interface.js:125
    _applyConcentration http://myfoundryserver:30000/modules/wire/module/resolver.js:544
    _step http://myfoundryserver:30000/modules/wire/module/resolver.js:99
    step http://myfoundryserver:30000/modules/wire/module/resolver.js:35
    _step http://myfoundryserver:30000/modules/wire/module/resolver.js:426
[utils.js:482:13](http://myfoundryserver:30000/modules/wire/module/utils.js)
    handleError http://myfoundryserver:30000/modules/wire/module/utils.js:482
    _activate http://myfoundryserver:30000/modules/wire/module/activation.js:359

I am using the latest release of DFred's (4.0.3) and WIRE (0.10.12) and it seems like this error occurs on any spell that requires concentration. Broken spells work fine after unticking Concentration, and vice versa, working spells start throwing the error by adding concentration. 

Not sure if this is an issue with WIRE or DFred's CE, but sine the module throwing the error is within WIRE I decided to post here.

**Comment by lambc42** [comment]
Looks like this issue was resolved by an update to DFred's Convenient Effects. After updating to DF CE 4.1.0 the issue is no longer occurring.

**Comment by lambc42** [comment]
Never mind, issue still occurs. I didn't have DF CE enabled before. 

Appears to still be an issue with WIRE.

**Comment by nimish-shah** [comment]
I'm seeing similar behavior in terms of casting a spell with concentration.  However, when I look at the error in the console, it has this error message:

utils.js:482 A technical error occurred. Please check the console error log and notify the GM. TypeError: ceApi.findEffectByName(...).convertToActiveEffectData is not a function
    at Resolver._applyConcentration (resolver.js:551:70)
    at async Resolver._step (resolver.js:99:13)
    at async Resolver.step (resolver.js:35:13)
    at async Resolver._step (resolver.js:426:13)
    at async Resolver.step (resolver.js:35:13)
    at async Resolver.start (resolver.js:26:9)
    at async activation.js:356:17
    at async Semaphore._try (commons.js:13652:19)

I'm guessing that DFreds Convenient Effects api may have had a breaking change in one of its recent versions and that's what's causing it.   It would be good for WIRE to support the latest.

**Comment by teroparvinen** [comment]
This was probably fixed with WIRE 0.11. Let me know if you keep running into problems.
