### ISSUE TITLE
[Feature Request] Support for once per turn damage

### ISSUE THREAD

**Issue by hanhmchau** [teroparvinen/foundry-wire#49]
### Context

My DnD 5e group regularly uses features that are along the line of "Once per turn when you hit you deal 1d4 extra damage", "The first time you hit in your turn you deal 6d6 extra damage", etc. A few examples are the Rogue's Sneak Attack, the Aasimar's Radiant Soul, the Zealot Barbarian's Divine Fury feature.

The way we usually deal with this is creating duplicate weapons like:
- Greatsword
- Greatsword (Divine Fury)
- Greatsword (Radiant Soul)
- Greatsword (Divine Fury, Radiant Soul)

The character with this weapon also possibly has Great Weapon Master, which is per attack, which leads to us now having more duplicate weapons... This is extremely clunky and a big hassle whenever a character gets a new weapon.

I am aware of your feature [Item Variants](https://github.com/teroparvinen/foundry-wire/wiki/Features#variants) and it goes a long way towards fixing our problem! However, it seems to me that you can't really combine variants. We would still have to make a Divine Fury variant, a Radiant Soul variant, then a Divine Fury + Radiant Soul variant.

Another, though lesser inconvenience is that every attack our barbarian player will have to make an extra click to choose which variant. This is very small, but can pile up as martials do make quite many attacks.

I would like to request a feature that automates this process as much as possible.

### The ask

In a weapon's Damage Formula area, for each damage parts, to add a field which allows customization of whether the damage part is:
- Every attack (default)
- Once on each of your turns (applies on the first hit you make this turn, but only when it is your turn)
- Once on each turn (applies on the first hit you make in any turn, which can include Opportunity Attacks)

Then, when rolling Damage on the attack roll/damage card, the player will have an option to click "apply once-per-turn bonuses". This means they will only have to make an extra click one attack out of the multiple they might be making.

Ideally, I would love to have an option for this to be fully automated. With this option, the system will automatically apply all the Once-per-turn damage parts if this is a character's first hit in a turn. All the hits afterwards will not add those damage parts.

Please let me know your thoughts and if it is already possible to do this, my apologies.

Great work on the module so far, it looks amazing!

**Comment by teroparvinen** [comment]
If I understand this correctly, some other things that belong to this category are battlemaster maneuvers and paladin smites.

Currently, the intended way for this to happen with WIRE is:

1. Roll to attack
2. Decide to apply the ability/feature affecting damage
3. Activate the ability/feature
4. Roll damage and gain the bonus granted by the ability

If you want to check out how this is supposed to work in practice, have a look at the paladin smite ability that comes with the WIRE SRD.

I think many abilities like sneak that you want to apply based on some other rule based conditions and the decision of the player work best keeping things simple and having the player activate them when needed. If you want to go further, abilities that automatically trigger on the first hit each turn can be automated like this:

1. Create a feature on the character, call it e.g. "Bonus damage each round"
2. On the feature, in the effects tab, create a new passive effect. It should be automatically named after the feature.
3. Enable "Transfer Effect to Actor" (this makes it a passive ability that is always on)
4. Under "Conditional Effects", add a condition: Start of target's turn → Apply over time effects
5. Save the effect
6. Create another effect on the feature's effect tab. Call it something to distinguish it, like "Damage modifier".
7. On this effect, set "Application phase" to "Over time" so the passively active effect applies this whenever the turn starts.
8. Add two conditions to this effect: End of target's turn → End the effect and Hits with any attack (or whatever is applicable) → End the effect. This will get rid of the bonus after the first hit or when the character's turn ends.
9. On the effect's effect tab, add a row to apply the actual damage bonus, e.g. system.bonuses.mwak.damage to "+1d6"
10.

Multiple abilities should work together just fine like this.

Let me know how this works out for you.

**Comment by teroparvinen** [comment]
I am closing this issue because as far as I can tell, the above solution should take care of it. Let me know if there is something not covered and I will reopen.
