### ISSUE TITLE
Problem With Casting Non-Round Templates

### ISSUE THREAD

**Issue by lacktheknack** [teroparvinen/foundry-wire#52]
Everything works great when casting a template-based spell with a round or radius template, but with squares and cones, it obliterates itself.

Error message implies that I've left a field in the spell details blank:
![image](https://github.com/teroparvinen/foundry-wire/assets/137741576/3f1d2ff9-2ee6-49b0-959a-108b76f4ceab)

I fixed this one once by changing the item sheet I was using, and the "target" field was empty even though it hadn't been before.  This time, that's not working.
![image](https://github.com/teroparvinen/foundry-wire/assets/137741576/530d4019-963c-4fbc-acfd-ffeba132a887)

Again, this spell works great if I change it to "radius", but "cube" just won't take.

**Comment by lacktheknack** [comment]
Have confirmed that it claims my spell's "value" is empty 
![image](https://github.com/teroparvinen/foundry-wire/assets/137741576/e3499de3-f942-4035-a661-5d1e53c965df)

It has a value in the sheet.

**Comment by DreamingHero1997** [comment]
Strange, I cannot replicate this issue, although in the previous version of WIRE I did have this issue of the value not changing there.

**Comment by lacktheknack** [comment]
I still have it, and I'm up to date.

The fix is to disable WIRE, set the size value, then re-enable WIRE, and it'll all work fine, so WIRE is actively blocking the sheet from writing to system.target.value.

**Comment by teroparvinen** [comment]
I have replicated this and a fix will be coming with the next update. For the bug to manifest, this has to be a brand new spell created without a "stock" value for the field, if you import an SRD/other item and modify it, it will use the hidden original value at first and not fail on validation.
