### ISSUE TITLE
Automated Animations triggering multiple times

### ISSUE THREAD

**Issue by callmeGeorgeRR** [teroparvinen/foundry-wire#54]
When using Automated animations the animation sequences are triggering twice. This sometimes occurs back to back such as with melee weapon attacks or ranged attacks like firebolt. Other times, like my setup of Thunder Step, it will trigger the teleport ring twice. Once during the target selections/template phase. Once during the damage phase. 

This occurs on every animation I trigger in some form or fashion. I have attached videos of the longsword and firebolt attacks triggering multiple times at a time for a signle attack. I have also attached a video of the teleport animation being triggered twice during the two phases of the Thunder Step spell.

I am using v11 build 308 and DnD 2.3.1 with 42 active modules. This occurs on a local copy of foundry and on a Forge installation. I have tried is with just WIRE and Automated animations and their dependencies and it still occurs.

https://github.com/teroparvinen/foundry-wire/assets/98905472/f6144b05-f656-4a2f-9599-67201d94be1e

https://github.com/teroparvinen/foundry-wire/assets/98905472/02042fc4-37fa-4d79-8404-855edd122be6

https://github.com/teroparvinen/foundry-wire/assets/98905472/db3204e8-d079-42d7-af16-15cc071f7b50

**Comment by YenBenGrey** [comment]
This is also happening to me in my world. The API has changed in AA, Whistler is fixing it in an upcoming release. 
In the meantime it’s not affecting my gameplay it just looks a bit Matrix-esque for a while.
