### ISSUE TITLE
Uncontrolled Animation/Effect Application

### ISSUE THREAD

**Issue by lacktheknack** [teroparvinen/foundry-wire#57]
Tried to implement Alchemist's Fire and was absolutely buried in overzealous effect and animation application.

![image](https://github.com/teroparvinen/foundry-wire/assets/137741576/2eb25f37-23e7-4157-94e7-d28417fea108)

(It has to be removed manually because if the final flask removes itself, WIRE breaks trying to execute it.)

![image](https://github.com/teroparvinen/foundry-wire/assets/137741576/30a1434c-b7ef-4f71-ac0d-00b47ba26d04)

![image](https://github.com/teroparvinen/foundry-wire/assets/137741576/a24ae897-bd17-427e-8078-45bb75c03d21)

![image](https://github.com/teroparvinen/foundry-wire/assets/137741576/9b0ade5b-3a6c-4a5b-a4a4-97f476697286)

Expected workflow:
-On its turn, the attacker targets another token and uses the item.
-Auto animation plays of attacker throwing a flask at the target.
-Item (noted as self-using ammunition) decrements its inventory count.
-If the attack hits, effect is applied to target.

-On the target's turn, attacker can roll and apply damage.
-Target may Use Action to roll a Dex check to remove the effect.
-On success, effect is removed from target.

Actual (extremely funny) workflow:
-On its turn, the attacker targets another token and uses the item.
-Auto animation plays of attacker throwing a flask at the target.
-Item (noted as self-using ammunition) decrements its inventory count.
--Effect is immediately applied to the attacker any time the count changes, causing them to burst into flames.
-If the attack hits, effect is applied to target.
---Auto animation plays of attacker throwing a flask at the target.

-On the target's turn, attacker can roll and apply damage.
--Auto animation plays of attacker throwing a flask at the target.
-Target may Use Action to roll a Dex check to remove the effect.
--Auto animation plays of attacker throwing a flask at the target.
-On success, effect is removed from target.
--Auto animation plays of attacker throwing a flask at the target.

--On attackers next turn, auto animation plays of attacker throwing a flask at themselves.
--Attacker can take an action to roll a Dex check to remove the effect, but no target for the roll is found.  Attacker is doomed to burn to death.

While very funny, I cannot imagine this was the intended use case of WIRE.

**Comment by teroparvinen** [comment]
I expect most AA bugs to be resolved with the next update. Feel free to open again if there's still something after that
