### ISSUE TITLE
Feature - Out of turn auras trigger

### ISSUE THREAD

**Issue by thatlonelybugbear** [teroparvinen/foundry-wire#6]
RAW and Spirit Guardians spell in mind as an example.
When a token is forced, out of its combat turn, to enter a template, for the first time it should trigger the overtime damage.

I will leave this comment here, as I am trying to figure my way around the module and maybe create a PR to include this special condition case.

**Comment by teroparvinen** [comment]
Right, the functionality is currently "enters the area on its turn", not "enters the area on a turn". Are these both needed, i.e. is there a spell that requires entering on the actor's own turn or should I just switch this to update all actors every turn?

**Comment by thatlonelybugbear** [comment]
Hmm, from the top of my head I am not 100% sure whether there is a specific case that would **need** the `own turn` distinction or not.
Will need to give it a think

**Comment by thatlonelybugbear** [comment]
It makes sense! Thanks 👍
