### ISSUE TITLE
TypeError: semaphore is not a constructor

### ISSUE THREAD

**Issue by paulo-roger** [teroparvinen/foundry-wire#8]
Hi! First congrats for the amazing module! This is awesome.

I am getting this error when the module is loaded:
![console-error](https://i.imgur.com/GcI3vOI.png)

If you need more information let me know, we can debug in discord if you like: winterwulf#3118

**Comment by paulo-roger** [comment]
OK my stupid ass didn't had DAE installed, sorry.

I think you might want to add this as a dependency in the manifest.json so other idiots like me don't forget it lol.

Sorry again.

**Comment by teroparvinen** [comment]
DAE is not a hard dependency and should not be a hard dependency. What it brings to the table is the ability to edit Active Effects directly on the character. If you have a super character specific ability or a one off custom item, it is quite useful. However, if someone wants to play purely with the WIRE content packs (which will be more comprehensive in the future hopefully) or craft items in the items tab, you don't strictly need DAE.

So this is a genuine bug that was fixed, thanks for the report. I haven't really had the chance to try out all the various module combinations as I usually have the supported ones on when doing development so stuff like this is bound to happen in the beginning...

**Comment by paulo-roger** [comment]
Oh cool :) So I'm glad I helped a small bit
